### ISSUE TITLE
Field not found when creating container with video

### ISSUE THREAD

**Issue by oiproks** [radek-k/FFMediaToolkit#101]
When executing **MediaBuilder.CreateContainer(PathToFile).WithVideo(settings).Create();** I get an ExceptionUnhandled:

`System.MissingFieldException: 'Field not found: 'FFmpeg.AutoGen.AVStream.codec'.'`

Settings:
```
 var settings = new VideoEncoderSettings(width: img.Width, height: img.Height, framerate: 30, codec: VideoCodec.H264);
settings.EncoderPreset = EncoderPreset.Fast;
settings.CRF = 18;
```

![image](https://user-images.githubusercontent.com/7554991/153034705-73a7dc66-5dd8-4deb-9293-c83e45bccd67.png)

**Comment by radek-k** [comment]
Fixed in the v4.2.0 release.
