### ISSUE TITLE
Why "This library is not recommended for production use"?

### ISSUE THREAD

**Issue by javidsho** [radek-k/FFMediaToolkit#103]
Could you make it more specific what you mean by "production"? Generally any shipped product or server environments?
And why is it not suitable for some environments?

**Comment by hey-red** [comment]
This means "can have bugs, use with careful". 
Anyway, with latest version I have no issues with that library.

**Comment by javidsho** [comment]
Thanks for the response.
So, do you happen to know if ffmpeg is secure for server environments?

**Comment by radek-k** [comment]
It is not safe to use FFMediaToolkit on server to decode user uploaded videos. It may cause segfault and FatalExecutionEngineError when processing some files. As soon as these errors are fixed, the warning will be removed.
