### ISSUE TITLE
Request to provide basic code example for video conversion/compression

### ISSUE THREAD

**Issue by AlessandroMartinelli** [radek-k/FFMediaToolkit#106]
Hi,
could you please provide a short code example on how to use this library to compress a video (e.g. mp4) with some given parameters?

As of now you've provided examples as how to extract frames and/or informations from a video and how to create a video from image frames. But FFmpeg basic usage is just to convert/compress a video.

Thanks!
Alessandro

**Comment by radek-k** [comment]
FFMediaToolkit doesn't use FFmpeg tool itself, but its low-level API, which provides direct access to video frames. For video conversion I recommend using a FFmpeg command-line wrapper library such as [Xabe.FFmpeg](https://github.com/tomaszzmuda/Xabe.FFmpeg). It would be more reliable and easier to setup.

**Comment by AlessandroMartinelli** [comment]
Understood, thank you very much for pointing me in the right direction.
