### ISSUE TITLE
ImageSharp image -> ImageData ?

### ISSUE THREAD

**Issue by 515621078** [radek-k/FFMediaToolkit#119]
An ImageSharp image as
_var img = new Image<Rgba32>(size.Width, size.Height);_
file.Video.AddFrame() need ImageData

How does it convert?

**Comment by hey-red** [comment]
As I don't know how you load image and which pixel format it has, but here is example for Rgba32:

```C#
using var image = Image.Load<Rgba32>(@"/path/to/image.jpg");

// Copy to bytes
byte[] pixelBytes = new byte[image.Width * image.Height * Unsafe.SizeOf<Rgba32>()];
image.CopyPixelDataTo(pixelBytes);

var imageData = ImageData.FromArray(pixelBytes, ImagePixelFormat.Rgba32, image.Width, image.Height);

// Do something with ImageData
```

Replace Rgba32 with Rgb32 or another px format.

**Comment by 515621078** [comment]
Thanks！that's exactly what I needed!
