### ISSUE TITLE
System.NotSupportedException on MediaBuilder.CreateContainer(@"C:\videos\example.mp4")

### ISSUE THREAD

**Issue by Tarcash** [radek-k/FFMediaToolkit#129]
I got the latest version from Nuget 4.4.1 and I get the following exception on CreateContainer:

System.NotSupportedException
  HResult=0x80131515
  Message=Specified method is not supported.
  Source=FFmpeg.AutoGen
  StackTrace:
   at FFmpeg.AutoGen.DynamicallyLoadedBindings.<>c.<Initialize>b__2_1156()
   at FFmpeg.AutoGen.DynamicallyLoadedBindings.<>c.<Initialize>b__2_449()
   at FFmpeg.AutoGen.ffmpeg.av_version_info()
   at FFMediaToolkit.FFmpegLoader.LoadFFmpeg()
   at FFMediaToolkit.Encoding.Internal.OutputContainer.Create(String extension)
   at FFMediaToolkit.Encoding.MediaBuilder..ctor(String path, Nullable`1 format)
   at FFMediaToolkit.Encoding.MediaBuilder.CreateContainer(String path)
   at FlipLibrary.ImageCompiler.<ProcessMovie>b__14_0() in G:\GIT\ImageFlipper\FlipLibrary\ImageCompiler.cs:line 83
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

**Comment by hey-red** [comment]
FFmpeg version? Any 5.x.x build should work with latest library from nuget.

**Comment by Tarcash** [comment]
It is the latest version from Git:

G:\GIT\ImageFlipper\DesktopApp\bin\Debug>ffmpeg -version
ffmpeg version N-110344-g73ddcad990-20230422 Copyright (c) 2000-2023 the
FFmpeg developers
built with gcc 12.2.0 (crosstool-NG 1.25.0.152_89671bf)
configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static
--pkg-config=pkg-config --cross-prefix=x86_64-w64-mingw32- --arch=x86_64
--target-os=mingw32 --enable-gpl --enable-version3 --disable-debug
--enable-shared --disable-static --disable-w32threads --enable-pthreads
--enable-iconv --enable-libxml2 --enable-zlib --enable-libfreetype
--enable-libfribidi --enable-gmp --enable-lzma --enable-fontconfig
--enable-libvorbis --enable-opencl --disable-libpulse --enable-libvmaf
--disable-libxcb --disable-xlib --enable-amf --enable-libaom
--enable-libaribb24 --enable-avisynth --enable-chromaprint
--enable-libdav1d --enable-libdavs2 --disable-libfdk-aac --enable-ffnvcodec
--enable-cuda-llvm --enable-frei0r --enable-libgme --enable-libkvazaar
--enable-libass --enable-libbluray --enable-libjxl --enable-libmp3lame
--enable-libopus --enable-librist --enable-libssh --enable-libtheora
--enable-libvpx --enable-libwebp --enable-lv2 --disable-libmfx
--enable-libvpl --enable-openal --enable-libopencore-amrnb
--enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg
--enable-libopenmpt --enable-librav1e --enable-librubberband
--enable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt
--enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --disable-libdrm
--disable-vaapi --enable-libvidstab --enable-vulkan --enable-libshaderc
--enable-libplacebo --enable-libx264 --enable-libx265 --enable-libxavs2
--enable-libxvid --enable-libzimg --enable-libzvbi
--extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags=
--extra-ldflags=-pthread --extra-ldexeflags= --extra-libs=-lgomp
--extra-version=20230422
libavutil      58.  6.100 / 58.  6.100
libavcodec     60. 10.100 / 60. 10.100
libavformat    60.  5.100 / 60.  5.100
libavdevice    60.  2.100 / 60.  2.100
libavfilter     9.  5.100 /  9.  5.100
libswscale      7.  2.100 /  7.  2.100
libswresample   4. 11.100 /  4. 11.100
libpostproc    57.  2.100 / 57.  2.100

G:\GIT\ImageFlipper\DesktopApp\bin\Debug>

**Comment by hey-red** [comment]
This is FFmpeg 6.x, which is not supported by that library. 
To resolve this issue author should update FFmpeg.AutoGen(I think no major api changes between 5 and 6)
