### ISSUE TITLE
Disposing opened MediaFile crashes app

### ISSUE THREAD

**Issue by bhutten14** [radek-k/FFMediaToolkit#15]
I have this simple code and makes my app crash. I think it has something to do with the frames allocated memory. How do I handle this correctly, because I cannot dispose a frame?

                foreach (var file in files)
                {
                    using (var mediaFile = MediaFile.Open(file))
                    {
                        var frame = mediaFile.Video.ReadFrame(TimeSpan.FromMilliseconds(_frameTimeSpan));
                    }
                }

**Comment by radek-k** [comment]
Thank you for reporting this issue. I will try to fix it in the next days. Your code is correct, `ImageData` objects are disposed automatically.

**Comment by Claytonious** [comment]
We are also having this issue. Can we provide any info that would help diagnose the problem?

**Comment by Claytonious** [comment]
BTW, if I comment out this line: https://github.com/radek-k/FFMediaToolkit/blob/master/FFMediaToolkit/src/Decoding/MediaFile.cs#L86, then the crash goes away. Of course this probably creates some memory leaks, but just mentioning it in case that makes it clearer where the problem may be.

**Comment by Claytonious** [comment]
This fixes the crash, but might be more heavy-handed than you prefer: https://github.com/radek-k/FFMediaToolkit/pull/17.

**Comment by radek-k** [comment]
I've just released the fixed v2.1.1 version on [Nuget](https://www.nuget.org/packages/FFMediaToolkit/). I have deleted the `ffmpeg.avcodec_free_context()` call which can only be used manually in encoding. The `ffmpeg.avformat_close_input()` method calls it automatically.

**Comment by Claytonious** [comment]
Perfect - you just beat me to it: https://github.com/Claytonious/FFMediaToolkit/pull/new/fix/disposeCrashes2. ;-) Thank you!
