### ISSUE TITLE
Noisey stdout/stderr from ffmpeg while using NextFrame()

### ISSUE THREAD

**Issue by Claytonious** [radek-k/FFMediaToolkit#18]
While using FFMediaToolkit to process video frames, their is a ton of spam output from ffmpeg like ```[swscaler @ 0x7fcc08068000] deprecated pixel format used, make sure you did set range correctly```

Is there any way to suppress this stuff? When using this on a server, it can cause tons of log messages to be emitted to logging services, etc.

Thanks!

**Comment by radek-k** [comment]
I have added a FFMpeg log verbosity setting (see #19 ) which allows to choose `quiet`, `error`, `warning` or `verbose` level. It is released on Nuget as 2.2.0 version. If you set the `MediaToolkit.LogVerbosity` property to `LogLevel.Quiet`, you will not get any log messages.
