### ISSUE TITLE
There is no .ToBitmap() Method for ReadFrame(framecount)

### ISSUE THREAD

**Issue by cemalgulbeyaz** [radek-k/FFMediaToolkit#20]
var file = MediaFile.Open(@"C:\videos\movie.mp4");
for (int i = 0; i < file.Video.Info.FrameCount; i++)
{
    file.Video.ReadFrame(i).ToBitmap().Save($@"C:\images\frame_{i}.png");
}

I wrote a code from your Seample code but there is no ToBitmap Method. I using Visual Studio 16.4.1 and Project .Net Core 3.1 Windows Worm. Can you help me?
Screen Capture of Code;
![Adsız](https://user-images.githubusercontent.com/12149285/72181326-21cac980-33fa-11ea-91c7-30f79eeef372.png)

**Comment by radek-k** [comment]
Sorry for the inaccurate information in the readme. I`ve just updated it. Please read [the usage details](https://github.com/radek-k/FFMediaToolkit#usage-details). 

In a .NET Core project you should install the  [ImageSharp](https://github.com/SixLabors/ImageSharp) library from Nuget and add the following method to your `Program` class.
````c#
public static Image<Bgr24> ToBitmap(this ImageData imageData)
{
    return Image.LoadPixelData<Bgr24>(imageData.Data, imageData.ImageSize.Width, imageData.ImageSize.Height);
}
````

**Comment by radek-k** [comment]
The complete .NET Core sample app with [ImageSharp](https://github.com/SixLabors/ImageSharp) should look like this
````c#
using System;
using System.IO;
using FFMediaToolkit.Graphics;
using FFMediaToolkit.Decoding;
using SixLabors.ImageSharp;
using SixLabors.ImageSharp.PixelFormats;

namespace YourProjectNamespace
{
    public class Program
    {
        static void Main(string[] args)
        {
            var file = MediaFile.Open(@"C:\videos\movie.mp4");
            for (int i = 0; i < file.Video.Info.FrameCount; i++)
            {
                using(var fs = new FileStream($@"C:\images\frame_{i}.png", FileMode.Create))
                {
                    file.Video.ReadFrame(i).ToBitmap().SaveAsPng(fs);
                }
            }
        }
    }

    public static class Extensions
    {
        public static Image<Bgr24> ToBitmap(this ImageData imageData)
        {
            return Image.LoadPixelData<Bgr24>(imageData.Data, imageData.ImageSize.Width, imageData.ImageSize.Height);
        }
    }
}
````

**Comment by dev-masih** [comment]
@radek-k you sample code for me results in Access violation crash when reaches line `ReadFrame`. do you have any idea how to resolve that?

**Comment by alexchri** [comment]
> @radek-k you sample code for me results in Access violation crash when reaches line `ReadFrame`. do you have any idea how to resolve that?

I am hitting the same issue - any ideas here?

**Comment by radek-k** [comment]
> > @radek-k you sample code for me results in Access violation crash when reaches line `ReadFrame`. do you have any idea how to resolve that?
> 
> I am hitting the same issue - any ideas here?

@alexchri Please update FFMediaToolkit package to [v3.1.0](https://www.nuget.org/packages/FFMediaToolkit/3.1.0). I've just fixed this bug.

**Comment by MastalerzKamil** [comment]
> The complete .NET Core sample app with [ImageSharp](https://github.com/SixLabors/ImageSharp) should look like this
> 
> ```cs
> using System;
> using System.IO;
> using FFMediaToolkit.Graphics;
> using FFMediaToolkit.Decoding;
> using SixLabors.ImageSharp;
> using SixLabors.ImageSharp.PixelFormats;
> 
> namespace YourProjectNamespace
> {
>     public class Program
>     {
>         static void Main(string[] args)
>         {
>             try
>             {
>                 var file = MediaFile.Open(@"C:\videos\movie.mp4");
>                 for (int i = 0; i < file.Video.Info.FrameCount; i++)
>                 {
>                     using(var fs = new FileStream($@"C:\images\frame_{i}.png", FileMode.Create))
>                     {
>                         file.Video.ReadFrame(i).ToBitmap().SaveAsPng(fs);
>                     }
>                 }
>             }
>             catch(EndOfStreamException) { }
>         }
>     }
> 
>     public static class Extensions
>     {
>         public static Image<Bgr24> ToBitmap(this ImageData imageData)
>         {
>             return Image.LoadPixelData<Bgr24>(imageData.Data, imageData.ImageSize.Width, imageData.ImageSize.Height);
>         }
>     }
> }
> ```

@radek-k  It works for me but it generates `System.IO.EndOfStreamException` as I described on issue #43

**Comment by Ulakurak** [comment]
Kindly request you to update the Setup section. 
First of all the Zeranoe FFmpeg site link is not working.
I have used the https://www.gyan.dev/ffmpeg/builds/ link to get required binaries.
On MediaFile.Open(@"C:\videos\movie.mp4") there is error message: System.IO.DirectoryNotFoundException: 'Cannot found the default FFmpeg directory.
On Windows you have to specify a path to a directory containing the FFmpeg shared build DLL files

**Comment by hey-red** [comment]
@Ulakurak 
> On Windows you have to specify a path to a directory containing the FFmpeg shared build DLL files

Another way is nuget package with FFmpeg dll's. For example https://www.nuget.org/packages/ImageSharp.AVCodecFormats.Native/
It should work out of box with FFMediaToolkit.
