### ISSUE TITLE
Encode/Decode without putting/taking from a file

### ISSUE THREAD

**Issue by slymatt** [radek-k/FFMediaToolkit#21]
Hello,

Do you have a way to encode and decode without having the data in a file. I am trying to send the encoded byte data over a network. I have the bitmap data stored in a ImageData but dont know how to move on from there.

Thanks

**Comment by Dzoge** [comment]
I have a similar issue, I am reading raw camera output in RaspberryPI using MMALSharp library and want to read frames in Bitmap format for further processing.

**Comment by radek-k** [comment]
Currently, only files are supported, but I want to implement the following features:
**In the next v3.0 release:**
- decoding videos from a web URL (for example: `http://example.com/video.mp4`)

**In the future:**
- decoding video from RTSP streams and capturing devices (webcams)
- writing encoded video to a `System.IO.Stream` object
- streaming video using FFmpeg `avio`

@Dzoge Why do you want to use FFMediaToolkit to get frames from Raspberry PI camera? You should use an existing `OutputCaptureHandler` from `MMALSharp` or write a new one to get the bitmaps for processing.
