### ISSUE TITLE
Error opening Mp4 file

### ISSUE THREAD

**Issue by jeffwash** [radek-k/FFMediaToolkit#24]
Hi,

I'm very new to this, but while trying to open an mp4 file, I'm getting this exception.  What am I doing wrong?

System.Exception
  HResult=0x80131500
  Message=Failed to open the media file
  Source=FFMediaToolkit
  StackTrace:
   at FFMediaToolkit.Decoding.MediaFile.Open(String path, MediaOptions options) in C:\...\MediaFile.cs:line 68

Inner Exception 1:
DllNotFoundException: Unable to load DLL 'avutil.56': The specified module could not be found.

**Comment by radek-k** [comment]
You have to use **"shared" (with included DLL files) FFmpeg build** from [Zeranoe FFmpeg site](https://ffmpeg.zeranoe.com/builds/) with **the same architecture as your project.** 
![zeranoe-ffmpeg-guide](https://user-images.githubusercontent.com/49524121/77427438-b9736d80-6dd6-11ea-97dc-fbd9c9e36ab6.png)
*(Zeranoe FFmpeg download menu)*

If you want to use 64-bit FFmpeg, you should go to the `Build` tab in the Visual Studio project properties and **disable the `Prefer 32-bit option`**:

![vs-build-settings](https://user-images.githubusercontent.com/49524121/61172052-c5d4d480-a57f-11e9-9754-c95fbe741143.jpg)

---
***In the next FFMediaToolkit release (v3.0.0) the appropriate FFmpeg DLLs will be included in the Nuget package, so you won't have to download and configure them manually.***

**Comment by jeffwash** [comment]
Fantastic!!!  That worked great!

FYI, I’m glad that your error message “Cannot found FFmpeg directory" Is unique.  It helped me trace down where to put the files.

Cheers!
-Jeff
