### ISSUE TITLE
Frames count

### ISSUE THREAD

**Issue by korch-noobster** [radek-k/FFMediaToolkit#28]
Hello! Got a question - im trying to increase frames count, like getting every 100 frame, but it starts show something strange.It displays same frames in different order. Works well on smaller steps. Every 10th frame was displayed correctly. But every 20 - completly wrong. Could you help me with  that?

**Comment by korch-noobster** [comment]
Also it doesnt reads correctly frames amount of video

**Comment by radek-k** [comment]
What version of FFMediaToolkit, OS and FFmpeg are you using? What video file have you tried to decode(file extension/codec name/fps/...)? Is this video variable frame rate?
The number of frames calculation and frame access methods works well with constant frame rate videos.

**Comment by korch-noobster** [comment]
oh. Thanks. The problem was in variable framerate.
