### ISSUE TITLE
Getting System.AccessViolationException when splitting video into frames

### ISSUE THREAD

**Issue by shubmittal** [radek-k/FFMediaToolkit#32]
I am using ffmpeg to extract frames and iterate over them. The codes iterates correctly over few frames and then then randomly throws error

"System.AccessViolationException: 'Attempted to read or write protected memory. This is often an indication that other memory is corrupt.'
Any suggestions on how to resolve it? System details and screenshot below:

System Details: OS: Windows TargetFramework: .netCore3.1 Nugets: FFMediaToolkit v3.0.0 and SixLabors.ImageSharp v1.0.0 Shared dlls copied from: https://ffmpeg.zeranoe.com/builds/ for version 4.2.2

![image](https://user-images.githubusercontent.com/11534734/90136688-6e2c0e00-dd29-11ea-863b-097df4633658.png)

**Comment by SKProCH** [comment]
@radek-k i still expirience this exception on 3.1.0 release:
```
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at FFmpeg.AutoGen.ffmpeg+<>c.<.cctor>b__6_453(FFmpeg.AutoGen.AVDictionary**)
   at FFmpeg.AutoGen.ffmpeg.av_dict_free(FFmpeg.AutoGen.AVDictionary**)
   at FFMediaToolkit.Common.FFDictionary.OnDisposing()
   at FFMediaToolkit.Common.Wrapper`1[[FFmpeg.AutoGen.AVDictionary, FFmpeg.AutoGen, Version=4.3.0.1, Culture=neutral, PublicKeyToken=9b7632533a381715]].Disposing(Boolean)
   at FFMediaToolkit.Common.Wrapper`1[[FFmpeg.AutoGen.AVDictionary, FFmpeg.AutoGen, Version=4.3.0.1, Culture=neutral, PublicKeyToken=9b7632533a381715]].Finalize()
```

**Comment by Tom-da-Coder** [comment]
Me too have the exact same problem. After some frames it can randomly throw this error. I use the latest (yesterday) code from GitHub and the Zeranoe shared builds, 64-bit Windows. My program is in .NET Core 3.1.
I am converting mpeg1 files to images.

**Comment by Tom-da-Coder** [comment]
![image](https://user-images.githubusercontent.com/72502954/95335255-77f86a80-08af-11eb-94d0-dfe4cc3e0f21.png)

**Comment by Tom-da-Coder** [comment]
In Common.FFDictionary

**Comment by hey-red** [comment]
I guess this called by finalizer, that's why is it randomly throws exception.
So `!requireDisposing` should be `requireDisposing` because these dicts gets free inside avformat_open_input/avcodec_open2 functions.

**Comment by Tom-da-Coder** [comment]
Thank you for the answer I got by mail. I don't understand why I can see it here. But in any event I removed the "!" in front of requireDsiposing (above) and now I don't get any sudden accessvioloations, it works. Thanks!!!
