### ISSUE TITLE
EndOfStreamException: 'End of the file'

### ISSUE THREAD

**Issue by quocdai92** [radek-k/FFMediaToolkit#36]
Hi, I got the Exception below although the reader is still available. Please help me.
![image](https://user-images.githubusercontent.com/5414742/92424819-8cade980-f1af-11ea-991f-71a7147474c1.png)

**Comment by radek-k** [comment]
`FrameCount` value may be not accurate in Variable Frame Rate videos.
You can check it with the code below:
````c#
bool isFrameCountAccurate = file.Video.Info.IsFrameCountProvidedByContainer || !file.Video.Info.IsVariableFrameRate;
````
In the next release I will add a `bool TryReadFrame(int number, out ImageData frame)` method to the `VideoStream` class. The method will return `false` instead of throwing an exception.
