### ISSUE TITLE
Encoding not worked

### ISSUE THREAD

**Issue by quocdai92** [radek-k/FFMediaToolkit#37]
Hello, 
I'm using the sample code from wiki:
```csharp
// You can set there codec, bitrate, frame rate and many other options.
var settings = new VideoEncoderSettings(width: 1920, height: 1080, framerate: 30, codec: VideoCodec.H264);
settings.CRF = 17;
var file = MediaBuilder.CreateContainer(@"C:\videos\example.mp4").WithVideo(settings).Create();
while(file.Video.FramesCount < 300)
{
    file.Video.AddFrame(/*Your code*/);
}
```
But the result video can't play. saw the details I think something wrong. :( 
![image](https://user-images.githubusercontent.com/5414742/92429234-83c31500-f1bb-11ea-89bb-a418f9fbe22c.png)
![image](https://user-images.githubusercontent.com/5414742/92429241-87ef3280-f1bb-11ea-883c-918007a2f4ab.png)

**Comment by radek-k** [comment]
You should call `file.Dispose()` after encoding. I forgot about that when I was writing the sample code.
