### ISSUE TITLE
MediaFile.Video.ReadFrame() sometimes causes crash

### ISSUE THREAD

**Issue by UserTCQ** [radek-k/FFMediaToolkit#40]
I'm using .NET Core 3.1.
App runs fine if the crash doesn't happen.
It seems to happen randomly.
![image](https://user-images.githubusercontent.com/56994757/95991755-5a02ab00-0e57-11eb-84c3-6936045d1b71.png)
Code:
![image](https://user-images.githubusercontent.com/56994757/95991814-6c7ce480-0e57-11eb-9021-f2c7d7790619.png)

**Comment by redbaty** [comment]
I'm having this problem aswell.

I've narrowed it down to FFDictionary dispose method, especifacally when it calls.

`ffmpeg.av_dict_free(&ptr);`

not sure why yet.

**Comment by manojkumarvstrenser** [comment]
I also have the same issue. We could reproduce the issue in .NET core 3.1

`           var  _videoFile = MediaFile.Open(moviePath);
            ImageData data1 = _videoFile.Video.ReadFrame(new TimeSpan(0, 0, 0, 0, 15));
            _videoFile.Dispose();`

The Dispose() method is crashing some times.

**Comment by kskalski** [comment]
Not sure if that is really related, but I think there is a bug in FFDictinoary Dispose method, which I fixed here https://github.com/radek-k/FFMediaToolkit/pull/46
