### ISSUE TITLE
System.AccessViolationException:“尝试读取或写入受保护的内存。这通常指示其他内存已损坏。

### ISSUE THREAD

**Issue by 3400442579** [radek-k/FFMediaToolkit#49]
![image](https://user-images.githubusercontent.com/34226979/99038870-3ac77c80-25c1-11eb-8ddc-d6140861ae2a.png)

![image](https://user-images.githubusercontent.com/34226979/99038698-eae8b580-25c0-11eb-8913-d586d5a67df3.png)

**Comment by kskalski** [comment]
Most likely fixed by https://github.com/radek-k/FFMediaToolkit/pull/46
