### ISSUE TITLE
Error: "BC30668" ImageData is outdated, Type with embedded references are not supported

### ISSUE THREAD

**Issue by smartelligence** [radek-k/FFMediaToolkit#51]
I'm working with 
- VS2019 (v16.7.6) 
- VB# project 
- WPF application
- Windows 10, 64bit

I just downloaded/installed FFMediatoolkit and got this error message directly within my editor. 

I guess using VB# is the problem since you guys use C#.

Any suggestions?

**Comment by smartelligence** [comment]
Others have the same issue... https://stackoverflow.com/questions/65074332/ignore-compiler-error-bc30668-types-with-embedded-references-are-not-supported

**Comment by smartelligence** [comment]
This seems unsolvable since this is "by design"... In the documentation is noted: FFMediaToolkit will also work with any other graphics library that supports creating images from Span<byte>, byte array or memory pointer

Is there any change to circumvent the use of the ImageData data structure?

**Comment by radek-k** [comment]
With the latest release, you can write the decoded bitmap directly to the WPF `WriteableBitmap` buffer using the `TryReadFrameToPointer` method
````vb
Dim file As FileStream = New FileStream("path to the video file", FileMode.Open, FileAccess.Read)
Dim media As MediaFile = MediaFile.Load(file)
Dim bmp As WriteableBimap = New WriteableBitmap(media.Video.Info.FrameSize.Width, media.Video.Info.FrameSize.Height, 96, 96, PixelFormats.Bgr24, Nothing)
bmp.Lock()
Dim decoded As Boolean = media.Video.TryReadFrameToPointer(TimeSpan.FromMinutes(1), bmp.BackBuffer, bmp.BackBufferStride)
If decoded Then
    bmp.AddDirtyRect(New Int32Rect(0, 0, media.Video.Info.FrameSize.Width, media.Video.Info.FrameSize.Height))
End If
bmp.Unlock()
imageBox.Source = bmp
````
You can also convert `ImageData` to a byte array:
````vb
Dim data() As Byte = media.Video.ReadNextFrame().Data.ToArray()
````
