### ISSUE TITLE
How to use MediaOptions.DecoderOptions? (Question)

### ISSUE THREAD

**Issue by marksugrue** [radek-k/FFMediaToolkit#59]
MediaOptions.DecoderOptions is a dictionary of strings that get passed in on MediaFile.Open(filename, mediaOptions).

I can't seem to find documentation for this. Does it correspond to the ffmpeg commandline parameters? I've tried the following without success

mediaOptions.DecoderOptions.Add("f", "h264");

**Comment by radek-k** [comment]
`DecoderOptions` does not match all command-line parameters, but only the codec options listed in the FFmpeg documentation: https://www.ffmpeg.org/ffmpeg-codecs.html#Codec-Options. The `MediaFile` class is designed for extracting frames from a video to process them or export as bitmap data. If you want to simply convert a video file, you should use other libraries that call FFmpeg via command-line.
