### ISSUE TITLE
missing dll

### ISSUE THREAD

**Issue by medialearn** [radek-k/FFMediaToolkit#6]
Great project. I tried your example after loading the Nuget lib just to load a simple
video file to get the stats. This is what I got:

Unable to load DLL 'avutil.56': The specified module could not be found.

One thing to note the build for FFmpeg that particular dll is named avutil-56.dll 
I know it is seeing the directory for the dll because I specified it. What am I missing. 
Thank you...

**Comment by radek-k** [comment]
FFmpeg libraries must have the same architecture as the main application. If you want to use 64-bit FFmpeg, you should go to the **Build** tab in the project properties and **disable** the **Prefer 32-bit** option.

![vsbuildsettings](https://user-images.githubusercontent.com/49524121/61172052-c5d4d480-a57f-11e9-9754-c95fbe741143.jpg)

**Comment by alexchri** [comment]
I have this issue as well even when using the correct 32 bit dll as noted in the instructions. I have un-selected "Prefer 32-bit" and overridden the property to found to a specific folder with the 32 bit dlls i have downloaded - but it still hits this dll not found error. 
I am trying this in a sample .net core project. Are there further steps I can try?
