### ISSUE TITLE
Pauseable feature wanted

### ISSUE THREAD

**Issue by shyakocat** [radek-k/FFMediaToolkit#66]
I happen to find this treasure project.

When encoding video from images, how to pause the process, such as `Serialize` or something else to restore the current status. Maybe the wait time is too long and the user close the program, or worse, the program crash or the laptop out of power. To make program robost, it is good when user can resume the render schedule from last frame.

**Comment by radek-k** [comment]
It's a great idea, but I'm not sure it's even possible. However, I will try to implement it in the future.

**Comment by yodadude2003** [comment]
This could only work with certain container formats that support appending frames after initial encoding.  For example, formats like MP4 I doubt could use such a feature but more robust muxers like MPEG-TS might work better.
