### ISSUE TITLE
Can this library be used to stream video?

### ISSUE THREAD

**Issue by SuperJMN** [radek-k/FFMediaToolkit#75]
Excuse me for the question instead of an issue. 

I would like to create a stream using sequences of still pictures (30 images per second). I'm looking for a library to create the video stream (optionally, with audio), in order to consume it by an application like VLC or similar.

Is it possible? If so, could you please provide an example?

Big thanks in advance.

**Comment by radek-k** [comment]
No, this library doesn't support video streaming.
