### ISSUE TITLE
Error: Invalid data found when processing input

### ISSUE THREAD

**Issue by leopripos** [radek-k/FFMediaToolkit#76]
Hi, I'm trying to use FFMediaToolkit in Jetson using ffmpeg for jetson from [Nvidia FFmpeg](https://docs.nvidia.com/jetson/l4t/index.html#page/Tegra%20Linux%20Driver%20Package%20Development%20Guide/multimedia.html)

But it throws error when trying to open the file (mp4 and Codec: H264 - MPEG-4 AVC (part 10) (avc1)).
The code part `var file = MediaFile.Open(videoPath);`

Here the error:
```
Unhandled exception. System.Exception: Failed to open the media file
 ---> FFMediaToolkit.FFmpegException: An error occurred while opening the file Error code: -1094995529 : Invalid data found when processing input
at FFMediaToolkit.Decoding.Internal.InputContainer.MakeContainer(String url, MediaOptions options, AVFormatContextDelegate contextDelegate)
at FFMediaToolkit.Decoding.Internal.InputContainer.LoadFile(String path, MediaOptions options)
at FFMediaToolkit.Decoding.MediaFile.Open(String path, MediaOptions options) 
--- End of inner exception stack trace --- 
at FFMediaToolkit.Decoding.MediaFile.Open(String path, MediaOptions options)
at FFMediaToolkit.Decoding.MediaFile.Open(String path)
```

Could you help me how to solve this issue?

**Comment by leopripos** [comment]
I'm using the latest version BTW.

The ffmpeg share library `/usr/lib/aarch64-linux-gnu/`
```
libavcodec.so.57
libavcodec.so.57.107.100
libavdevice.so.57
libavdevice.so.57.10.100 
libavfilter.so.6 
libavfilter.so.6.107.100
libavformat.so.57
libavformat.so.57.83.100
libavresample.so.3
libavresample.so.3.7.0
libavutil.so.55
libavutil.so.55.78.10
```
So in my code, I added:
```csharp
FFmpeg.AutoGen.ffmpeg.LibraryVersionMap["avcodec"] = 57;
FFmpeg.AutoGen.ffmpeg.LibraryVersionMap["avdevice"] = 57;
FFmpeg.AutoGen.ffmpeg.LibraryVersionMap["avfilter"] = 6;
FFmpeg.AutoGen.ffmpeg.LibraryVersionMap["avformat"] = 57;
FFmpeg.AutoGen.ffmpeg.LibraryVersionMap["avutil"] = 55;
FFmpeg.AutoGen.ffmpeg.LibraryVersionMap["postproc"] = 54;
FFmpeg.AutoGen.ffmpeg.LibraryVersionMap["swresample"] = 2;
FFmpeg.AutoGen.ffmpeg.LibraryVersionMap["swscale"] = 4;
```

could you help me please?

**Comment by hey-red** [comment]
You process multiple files?
I noticed one thing - when I try to process multiple files in different threads (with different MediaFile instances) it crash with same error.
So, I put lock to my operation and it works without errors. Maybe FFmpeg.Autogen needs lock for some operations that uses shared resources?

**Comment by leopripos** [comment]
I don't process multiple files, just a single file.

I have fixed this one, I updated the ffmpeg version using [jocover/jetson-ffmpeg](https://github.com/jocover/jetson-ffmpeg).
It think it is because the version mismatch. And updated the library location to `/usr/bin`
