### ISSUE TITLE
wmv file  MediaFile.Video.TryGetFrame    return false

### ISSUE THREAD

**Issue by 3400442579** [radek-k/FFMediaToolkit#78]
test wmv:
[Wildlife.zip](https://github.com/radek-k/FFMediaToolkit/files/6362145/Wildlife.zip)

**Comment by hey-red** [comment]
Your ffmpeg build includes WMV9?
I just make simple test with my [windows build](https://www.nuget.org/packages/ImageSharp.AVCodecFormats.Native.win-x64/) and it works.

**Comment by 3400442579** [comment]
ffmpeg  WMV  to gif is ok, but  MediaFile.Video.TryGetFrame return false.
