### ISSUE TITLE
Add Audio Sountrack

### ISSUE THREAD

**Issue by BryanWilkins** [radek-k/FFMediaToolkit#85]
How do I add Audio soundtrack from a .wav file into a video that I made from a bunch of .png files?

How do I get data into the AudioData Structure

**Comment by radek-k** [comment]
At the moment it's not possible to add a soundtrack into a video. Audio features will be improved in the future.

**Comment by BryanWilkins** [comment]
Thanks for the reply.  

Just so others know, I was able to figure out how to mux it from a launched process from a command line ffmpeg call.

Not entirely ideal, but it worked.
