### ISSUE TITLE
Downloading M3U8 Streams

### ISSUE THREAD

**Issue by InteXX** [radek-k/FFMediaToolkit#90]
Can this tool be used to download an M3U8 stream?

For example, here's the command line I've been using:

```
ffmpeg -i https://domain.com/directory/playlist.m3u8 -c copy "D:\TargetFolder\TargetVideo.mp4"
```

But I'd like to move the task into managed code, hopefully with progress reporting.

What would be the `FFMediaToolkit` equivalent for this?

**Comment by radek-k** [comment]
M3U8 downloading is not supported.
