### ISSUE TITLE
Phone created portrait video frames shows rotated

### ISSUE THREAD

**Issue by artkh24** [radek-k/FFMediaToolkit#95]
Hi
when trying to get the frames from video created by phone using portrait mode all frames showing rotated by 90 degree

**Comment by ggolda** [comment]
Same problem. This issue is due to how vendors pack portrait videos in landscape format + add metadata with rotation parameter in it.

Currently FFMediaToolkit doesn't provide this metadata parameter for rotation with a video stream metadata dictionary and I had to use ffprobe to get it.
