### ISSUE TITLE
Applying video filter while encoding images into video

### ISSUE THREAD

**Issue by Oscar-Verver** [radek-k/FFMediaToolkit#98]
I'm trying to use this package to convert from a custom filetype somebody created into a filetype that can be uploaded onto Vimeo. I can extract images, and pair those up into a dfisheye 360 video projection, and encode those using the FFMediaToolkit. But in order to upload 360 to Vimeo I'll need an equirectangular projection. I can do this in FFmpeg through the command line, but can't figure out how to do it in this toolkit/don't know if this filter can be applied while encoding images. Using the settings library isn't working the way I expected it to work: settings.CodecOptions.Add("vf", "v360=dfisheye:equirect:ih_fov=185:iv_fov=185:yaw=-90"); //doesn't seem to do the trick. Without it my program outputs to dfisheye and with it still outputs the same dfisheye.

Would you be interested in helping me figure this out?

[source snippet.txt](https://github.com/radek-k/FFMediaToolkit/files/7538366/source.snippet.txt)

**Comment by yodadude2003** [comment]
FFMediaToolkit is not an API for accessing the ffmpeg tool itself, it is for managed access to the low level decoding, encoding, and seeking APIs that the ffmpeg tool also happens to use.

**Comment by Oscar-Verver** [comment]
Thanks yodadude2003; guess that resolves the question <3
